# -*- coding: utf-8 -*-
"""audio-modal-final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qONAibPFE3k8qLygwP4m-FoTKvHNl6o5

# STEP 0: Install & Import
"""

# ==============================================================================
# STEP 1: IMPORTS AND SETUP
# ==============================================================================

# Fix for librosa compatibility
import numpy as np
np.complex = complex
np.float = float

# General imports
import os, gc, time, shutil
from glob import glob
from tqdm.notebook import tqdm

# Audio processing
import librosa
import librosa.display
import matplotlib.pyplot as plt
import soundfile as sf

# Deep Learning
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
import torchvision.models as models
import torchvision.transforms as transforms
from torchvision.transforms import functional as TF

# Evaluation
from sklearn.metrics import accuracy_score, confusion_matrix, ConfusionMatrixDisplay
from sklearn.metrics import classification_report

# System monitoring (fixed version)
try:
    import GPUtil
    GPU_AVAILABLE = True
except ImportError:
    GPU_AVAILABLE = False
    print("GPUtil not available, skipping GPU monitoring")

import psutil

print("✅ All imports completed successfully!")
print(f"PyTorch version: {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")

# ==============================================================================
# STEP 2: DATA PREPROCESSING - SMART LOADING (SKIP IF EXISTS)
# ==============================================================================

# Define paths
base_path = "/kaggle/input/asvspoof2019-la/LA"
output_base = "/kaggle/working/mfcc_npy"

def check_preprocessing_done():
    """Check if preprocessing is already completed"""
    required_dirs = ["train", "dev", "eval"]

    for task in required_dirs:
        task_dir = os.path.join(output_base, task)
        if not os.path.exists(task_dir):
            return False

        # Check if directory has reasonable number of files
        files = glob(f"{task_dir}/*.npy")
        if len(files) < 100:  # Minimum expected files
            return False

    return True

# Check if preprocessing is done
preprocessing_done = check_preprocessing_done()
print(f"Preprocessing status: {'✅ COMPLETED' if preprocessing_done else '❌ NEEDED'}")

if not preprocessing_done:
    print("=" * 50)
    print("STEP 2: MFCC EXTRACTION (RUNNING...)")
    print("=" * 50)

    os.makedirs(output_base, exist_ok=True)

    # Protocol files mapping
    protocol_files = {
        "train": "ASVspoof2019.LA.cm.train.trn.txt",
        "dev": "ASVspoof2019.LA.cm.dev.trl.txt",
        "eval": "ASVspoof2019.LA.cm.eval.trl.txt"
    }

    def load_protocol(task):
        """Load protocol file and return list of (filename, label) tuples"""
        lines = []
        protocol_path = os.path.join(base_path, "ASVspoof2019_LA_cm_protocols", protocol_files[task])

        with open(protocol_path, 'r') as f:
            for line in f:
                parts = line.strip().split()
                fname, label = parts[1], parts[-1]
                lines.append((fname, label))

        print(f"Loaded {len(lines)} files for {task} set")
        return lines

    def extract_mfcc(task):
        """Extract MFCC features from audio files and save as .npy"""
        save_dir = os.path.join(output_base, task)
        os.makedirs(save_dir, exist_ok=True)

        protocol = load_protocol(task)
        audio_dir = os.path.join(base_path, f"ASVspoof2019_LA_{task}")
        saved, errors = 0, []

        print(f"🎵 Extracting MFCC for {task} set...")
        print(f"Total files to process: {len(protocol)}")

        for fname, label in tqdm(protocol, desc=f"Processing {task}"):
            input_file = os.path.join(audio_dir, "flac", f"{fname}.flac")
            output_file = os.path.join(save_dir, f"{fname}_{label}.npy")

            # Skip if already exists
            if os.path.exists(output_file):
                saved += 1
                continue

            try:
                # Load audio and extract MFCC
                y, sr = librosa.load(input_file, sr=16000)
                mfcc = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=40)
                np.save(output_file, mfcc)
                saved += 1

            except Exception as e:
                errors.append((fname, str(e)))

        print(f"✅ Task '{task}' completed.")
        print(f"Saved: {saved}, Errors: {len(errors)}")
        if errors:
            print("First 5 errors:")
            for err in errors[:5]:
                print(f"  {err[0]}: {err[1]}")

    # Extract MFCC for all sets
    extract_mfcc("train")
    extract_mfcc("dev")
    extract_mfcc("eval")

    print("🎉 MFCC extraction completed for all sets!")
else:
    print("=" * 50)
    print("STEP 2: MFCC EXTRACTION (SKIPPED - ALREADY EXISTS)")
    print("=" * 50)

    # Count existing files
    for task in ["train", "dev", "eval"]:
        task_dir = os.path.join(output_base, task)
        if os.path.exists(task_dir):
            files = glob(f"{task_dir}/*.npy")
            print(f"{task.capitalize()} set: {len(files)} files")
# ==============================================================================
# STEP 3: VISUALIZE SAMPLE AUDIO AND MFCC
# ==============================================================================

print("=" * 50)
print("STEP 3: VISUALIZATION")
print("=" * 50)

# Load sample audio for visualization
sample_files = glob("/kaggle/input/asvspoof2019-la/LA/ASVspoof2019_LA_train/flac/*.flac")
if sample_files:
    audio_path = sample_files[0]
    print(f"Loading sample: {os.path.basename(audio_path)}")

    # Load audio
    y, sr = librosa.load(audio_path, sr=16000)

    # Extract MFCC
    mfcc = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=40)

    # Plot
    plt.figure(figsize=(15, 6))

    plt.subplot(1, 3, 1)
    librosa.display.waveshow(y, sr=sr)
    plt.title("Audio Waveform")
    plt.xlabel("Time (s)")
    plt.ylabel("Amplitude")

    plt.subplot(1, 3, 2)
    librosa.display.specshow(mfcc, sr=sr, x_axis='time')
    plt.title("MFCC Features")
    plt.colorbar()

    plt.subplot(1, 3, 3)
    plt.imshow(mfcc, aspect='auto', origin='lower')
    plt.title("MFCC as Image")
    plt.xlabel("Time Frames")
    plt.ylabel("MFCC Coefficients")
    plt.colorbar()

    plt.tight_layout()
    plt.show()

    print(f"Audio shape: {y.shape}")
    print(f"MFCC shape: {mfcc.shape}")
    print(f"Sample rate: {sr} Hz")
# ==============================================================================
# STEP 4: CUSTOM DATASET CLASS FOR VIT
# ==============================================================================

print("=" * 50)
print("STEP 3: DATASET PREPARATION")
print("=" * 50)

class MFCCDataset(Dataset):
    """
    Custom Dataset for MFCC features compatible with Vision Transformer
    Handles variable-length MFCC sequences and converts them to fixed-size images
    """

    def __init__(self, mfcc_dir, target_size=224, max_length=500):
        self.files = glob(f"{mfcc_dir}/*.npy")
        self.labels = [0 if 'bonafide' in f else 1 for f in self.files]
        self.target_size = target_size
        self.max_length = max_length

        print(f"Dataset initialized with {len(self.files)} files")
        print(f"Bonafide samples: {self.labels.count(0)}")
        print(f"Spoof samples: {self.labels.count(1)}")

    def __len__(self):
        return len(self.files)

    def __getitem__(self, idx):
        # Load MFCC data
        path = self.files[idx]
        data = np.load(path)  # Shape: (n_mfcc, time_frames)
        label = self.labels[idx]

        # Normalize the data
        data = (data - np.mean(data)) / (np.std(data) + 1e-9)

        # Handle variable time length
        n_mfcc, time_frames = data.shape

        # Pad or truncate to max_length
        if time_frames < self.max_length:
            # Pad with zeros
            pad_width = self.max_length - time_frames
            data = np.pad(data, ((0, 0), (0, pad_width)), mode='constant', constant_values=0)
        elif time_frames > self.max_length:
            # Truncate to max_length
            data = data[:, :self.max_length]

        # Now data shape is (n_mfcc, max_length)
        # Convert to tensor and add channel dimension
        data_tensor = torch.tensor(data, dtype=torch.float32).unsqueeze(0)  # (1, n_mfcc, max_length)

        # Resize to target_size x target_size for ViT
        data_resized = TF.resize(data_tensor, (self.target_size, self.target_size), antialias=True)

        # Repeat to create 3 channels (RGB-like) for ViT: (1, 224, 224) -> (3, 224, 224)
        data_final = data_resized.repeat(3, 1, 1)

        return data_final, torch.tensor(label, dtype=torch.long)

# Create datasets
train_dataset = MFCCDataset("/kaggle/working/mfcc_npy/train")
dev_dataset = MFCCDataset("/kaggle/working/mfcc_npy/dev")

# Create data loaders with optimized settings
train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True, num_workers=2, pin_memory=True)  # Reduced batch size
dev_loader = DataLoader(dev_dataset, batch_size=16, shuffle=False, num_workers=2, pin_memory=True)

# Test the dataset
print("\n🧪 Testing dataset...")
sample_data, sample_label = train_dataset[0]
print(f"Sample data shape: {sample_data.shape}")
print(f"Sample label: {sample_label}")
print(f"Data type: {sample_data.dtype}")
print(f"Data range: [{sample_data.min():.3f}, {sample_data.max():.3f}]")

print("✅ Dataset preparation completed successfully!")

# ==============================================================================
# STEP 5: VISION TRANSFORMER MODEL SELECTION
# ==============================================================================

print("=" * 50)
print("STEP 4: MODEL SELECTION")
print("=" * 50)

# Available ViT models with their specifications
VIT_MODELS = {
    "vit_b_16": {
        "model_func": "vit_b_16",
        "weights": "ViT_B_16_Weights.DEFAULT",
        "params": "86M",
        "description": "ViT-Base/16 - Good balance of performance and speed"
    },
    "vit_b_32": {
        "model_func": "vit_b_32",
        "weights": "ViT_B_32_Weights.DEFAULT",
        "params": "88M",
        "description": "ViT-Base/32 - Faster, smaller patches"
    },
    "vit_l_16": {
        "model_func": "vit_l_16",
        "weights": "ViT_L_16_Weights.DEFAULT",
        "params": "304M",
        "description": "ViT-Large/16 - More powerful but needs more memory"
    },
    "vit_l_32": {
        "model_func": "vit_l_32",
        "weights": "ViT_L_32_Weights.DEFAULT",
        "params": "306M",
        "description": "ViT-Large/32 - Large model with smaller patches"
    }
}

def print_model_options():
    """Print available model options"""
    print("Available Vision Transformer Models:")
    print("=" * 60)
    for key, info in VIT_MODELS.items():
        print(f"{key:12} | {info['params']:>6} | {info['description']}")
    print("=" * 60)

print_model_options()

# Model selection - Change this to try different models
SELECTED_MODEL = "vit_b_32"  # You can change this to: vit_b_16, vit_b_32, vit_l_16, vit_l_32

print(f"\n🎯 Selected Model: {SELECTED_MODEL}")
print(f"Description: {VIT_MODELS[SELECTED_MODEL]['description']}")

# Load the selected model
from torchvision.models import vit_b_16, vit_b_32, vit_l_16, vit_l_32
from torchvision.models import ViT_B_16_Weights, ViT_B_32_Weights, ViT_L_16_Weights, ViT_L_32_Weights

# Model loading function
def load_vit_model(model_name):
    """Load Vision Transformer model based on name"""
    if model_name == "vit_b_16":
        weights = ViT_B_16_Weights.DEFAULT
        model = vit_b_16(weights=weights)
    elif model_name == "vit_b_32":
        weights = ViT_B_32_Weights.DEFAULT
        model = vit_b_32(weights=weights)
    elif model_name == "vit_l_16":
        weights = ViT_L_16_Weights.DEFAULT
        model = vit_l_16(weights=weights)
    elif model_name == "vit_l_32":
        weights = ViT_L_32_Weights.DEFAULT
        model = vit_l_32(weights=weights)
    else:
        raise ValueError(f"Unknown model: {model_name}")

    return model, weights

print(f"Loading {SELECTED_MODEL}...")
model, weights = load_vit_model(SELECTED_MODEL)

# Get the input features of the classification head
if hasattr(model, 'heads'):
    in_features = model.heads[0].in_features if hasattr(model.heads[0], 'in_features') else model.heads.head.in_features
elif hasattr(model, 'head'):
    in_features = model.head.in_features
else:
    # For some models, check classifier
    in_features = model.classifier.in_features

print(f"Original classification head input features: {in_features}")

# Replace the classification head for binary classification
if hasattr(model, 'heads'):
    model.heads = nn.Sequential(
        nn.Dropout(0.2),
        nn.Linear(in_features, 512),
        nn.GELU(),
        nn.Dropout(0.1),
        nn.Linear(512, 2)  # 2 classes: bonafide, spoof
    )
elif hasattr(model, 'head'):
    model.head = nn.Sequential(
        nn.Dropout(0.2),
        nn.Linear(in_features, 512),
        nn.GELU(),
        nn.Dropout(0.1),
        nn.Linear(512, 2)
    )
else:
    model.classifier = nn.Sequential(
        nn.Dropout(0.2),
        nn.Linear(in_features, 512),
        nn.GELU(),
        nn.Dropout(0.1),
        nn.Linear(512, 2)
    )

# Move model to GPU if available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)

print(f"Model moved to device: {device}")

# Count parameters
total_params = sum(p.numel() for p in model.parameters())
trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"Total parameters: {total_params:,}")
print(f"Trainable parameters: {trainable_params:,}")

# ==============================================================================
# STEP 6: UTILITY FUNCTIONS (FIXED GPU MONITORING)
# ==============================================================================

def print_gpu_usage():
    """Print current GPU memory usage - Fixed version"""
    if torch.cuda.is_available():
        try:
            if GPU_AVAILABLE:
                gpus = GPUtil.getGPUs()
                for gpu in gpus:
                    # Fixed: use correct attribute names
                    memory_used = getattr(gpu, 'memoryUsed', 'N/A')
                    memory_total = getattr(gpu, 'memoryTotal', 'N/A')
                    memory_percent = getattr(gpu, 'memoryPercent', getattr(gpu, 'memoryUtil', 0) * 100)
                    print(f"GPU {gpu.id}: {memory_used}MB / {memory_total}MB ({memory_percent:.1f}%)")
            else:
                # Fallback to PyTorch CUDA info
                for i in range(torch.cuda.device_count()):
                    memory_reserved = torch.cuda.memory_reserved(i) / 1024**2
                    memory_allocated = torch.cuda.memory_allocated(i) / 1024**2
                    print(f"GPU {i}: {memory_allocated:.0f}MB allocated, {memory_reserved:.0f}MB reserved")
        except Exception as e:
            print(f"GPU monitoring error: {e}")
            # Simple fallback
            if torch.cuda.is_available():
                print(f"CUDA device: {torch.cuda.get_device_name()}")
    else:
        print("CUDA not available")

def print_system_stats():
    """Print system resource usage"""
    mem = psutil.virtual_memory()
    print(f"RAM Used: {mem.used // (1024**2)}MB / {mem.total // (1024**2)}MB ({mem.percent:.1f}%)")
    print_gpu_usage()

print("\n📊 Current system status:")
print_system_stats()

# ==============================================================================
# STEP 6: TRAINING FUNCTION
# ==============================================================================

print("=" * 50)
print("STEP 6: TRAINING SETUP")
print("=" * 50)

def train_model(model, train_loader, dev_loader, epochs=10, lr=1e-4, patience=3):
    """
    Train the Vision Transformer model with improved error handling
    """

    # Loss function and optimizer
    criterion = nn.CrossEntropyLoss()
    optimizer = torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=0.01)

    # Learning rate scheduler
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer, mode='min', factor=0.5, patience=2, verbose=True
    )

    # Training history
    history = {
        "train_loss": [], "train_acc": [],
        "val_loss": [], "val_acc": []
    }

    best_val_acc = 0.0
    patience_counter = 0

    print(f"🚀 Starting training for {epochs} epochs...")
    print(f"Training samples: {len(train_loader.dataset)}")
    print(f"Validation samples: {len(dev_loader.dataset)}")
    print(f"Batch size: {train_loader.batch_size}")
    print(f"Steps per epoch: {len(train_loader)}")

    for epoch in range(epochs):
        print(f"\n{'='*60}")
        print(f"EPOCH {epoch+1}/{epochs}")
        print(f"{'='*60}")

        start_time = time.time()

        # ============ TRAINING PHASE ============
        model.train()
        train_loss = 0.0
        train_correct = 0
        train_total = 0

        train_pbar = tqdm(train_loader, desc=f"Training Epoch {epoch+1}")
        for batch_idx, (data, target) in enumerate(train_pbar):
            try:
                data, target = data.to(device, non_blocking=True), target.to(device, non_blocking=True)

                # Zero gradients
                optimizer.zero_grad()

                # Forward pass
                output = model(data)
                loss = criterion(output, target)

                # Backward pass
                loss.backward()

                # Gradient clipping for stability
                torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)

                optimizer.step()

                # Statistics
                train_loss += loss.item()
                _, predicted = torch.max(output.data, 1)
                train_total += target.size(0)
                train_correct += (predicted == target).sum().item()

                # Update progress bar
                current_acc = 100. * train_correct / train_total
                train_pbar.set_postfix({
                    'Loss': f'{loss.item():.4f}',
                    'Acc': f'{current_acc:.2f}%'
                })

                # Memory cleanup every 50 batches
                if batch_idx % 50 == 0:
                    torch.cuda.empty_cache()

            except RuntimeError as e:
                if "out of memory" in str(e):
                    print(f"🚨 GPU out of memory at batch {batch_idx}. Clearing cache...")
                    torch.cuda.empty_cache()
                    gc.collect()
                    continue
                else:
                    raise e

        # Calculate training metrics
        epoch_train_loss = train_loss / len(train_loader)
        epoch_train_acc = 100. * train_correct / train_total

        # ============ VALIDATION PHASE ============
        model.eval()
        val_loss = 0.0
        val_correct = 0
        val_total = 0

        with torch.no_grad():
            val_pbar = tqdm(dev_loader, desc=f"Validation Epoch {epoch+1}")
            for data, target in val_pbar:
                try:
                    data, target = data.to(device, non_blocking=True), target.to(device, non_blocking=True)

                    output = model(data)
                    loss = criterion(output, target)

                    val_loss += loss.item()
                    _, predicted = torch.max(output.data, 1)
                    val_total += target.size(0)
                    val_correct += (predicted == target).sum().item()

                    # Update progress bar
                    current_acc = 100. * val_correct / val_total
                    val_pbar.set_postfix({
                        'Loss': f'{loss.item():.4f}',
                        'Acc': f'{current_acc:.2f}%'
                    })

                except RuntimeError as e:
                    if "out of memory" in str(e):
                        print(f"🚨 GPU out of memory during validation. Clearing cache...")
                        torch.cuda.empty_cache()
                        gc.collect()
                        continue
                    else:
                        raise e

        # Calculate validation metrics
        epoch_val_loss = val_loss / len(dev_loader)
        epoch_val_acc = 100. * val_correct / val_total

        # Update learning rate scheduler
        scheduler.step(epoch_val_loss)

        # Save metrics
        history["train_loss"].append(epoch_train_loss)
        history["train_acc"].append(epoch_train_acc)
        history["val_loss"].append(epoch_val_loss)
        history["val_acc"].append(epoch_val_acc)

        # Print epoch summary33
        epoch_time = time.time() - start_time
        print(f"\nEPOCH {epoch+1} SUMMARY:")
        print(f"Train Loss: {epoch_train_loss:.4f} | Train Acc: {epoch_train_acc:.2f}%")
        print(f"Val Loss: {epoch_val_loss:.4f} | Val Acc: {epoch_val_acc:.2f}%")
        print(f"Time: {epoch_time:.2f}s")
        print(f"Learning Rate: {optimizer.param_groups[0]['lr']:.2e}")

        # Print system stats
        try:
            print_system_stats()
        except Exception as e:
            print(f"System stats error: {e}")

        # Early stopping and model saving
        if epoch_val_acc > best_val_acc:
            best_val_acc = epoch_val_acc
            patience_counter = 0
            # Save best model
            model_save_path = f"/kaggle/working/best_{SELECTED_MODEL}_mfcc_model.pth"
            torch.save(model.state_dict(), model_save_path)
            print(f"🎯 New best validation accuracy: {best_val_acc:.2f}% - Model saved!")
        else:
            patience_counter += 1
            print(f"Patience: {patience_counter}/{patience}")

        # Early stopping
        if patience_counter >= patience:
            print(f"🛑 Early stopping triggered after {epoch+1} epochs")
            break

        # Memory cleanup
        torch.cuda.empty_cache()
        gc.collect()

    print(f"\n🏁 Training completed!")
    print(f"Best validation accuracy: {best_val_acc:.2f}%")

    return history

# ==============================================================================
# STEP 8: START TRAINING
# ==============================================================================

print("=" * 50)
print("STEP 7: TRAINING EXECUTION")
print("=" * 50)

# Start training with adjusted parameters
history = train_model(
    model=model,
    train_loader=train_loader,
    dev_loader=dev_loader,
    epochs=10,  # Increased epochs
    lr=5e-5,    # Slightly lower learning rate for stability
    patience=4  # More patience
)

# ==============================================================================
# STEP 9: RESULTS VISUALIZATION
# ==============================================================================

print("=" * 50)
print("STEP 8: RESULTS VISUALIZATION")
print("=" * 50)

# Plot training history
plt.figure(figsize=(15, 5))

# Loss plot
plt.subplot(1, 3, 1)
plt.plot(history['train_loss'], label='Training Loss', marker='o')
plt.plot(history['val_loss'], label='Validation Loss', marker='s')
plt.title('Model Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.grid(True)

# Accuracy plot
plt.subplot(1, 3, 2)
plt.plot(history['train_acc'], label='Training Accuracy', marker='o')
plt.plot(history['val_acc'], label='Validation Accuracy', marker='s')
plt.title('Model Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy (%)')
plt.legend()
plt.grid(True)

# Combined plot
plt.subplot(1, 3, 3)
plt.plot(history['train_loss'], label='Train Loss', alpha=0.7)
plt.plot(history['val_loss'], label='Val Loss', alpha=0.7)
plt.ylabel('Loss', color='blue')
plt.tick_params(axis='y', labelcolor='blue')

# Add accuracy on secondary y-axis
ax2 = plt.gca().twinx()
ax2.plot(history['train_acc'], label='Train Acc', color='red', alpha=0.7)
ax2.plot(history['val_acc'], label='Val Acc', color='orange', alpha=0.7)
ax2.set_ylabel('Accuracy (%)', color='red')
ax2.tick_params(axis='y', labelcolor='red')

plt.title('Loss & Accuracy Combined')
plt.xlabel('Epoch')
plt.grid(True)

plt.tight_layout()
plt.show()

# ==============================================================================
# STEP 10: MODEL EVALUATION
# ==============================================================================

print("=" * 50)
print("STEP 9: MODEL EVALUATION")
print("=" * 50)

def evaluate_model(model, data_loader, dataset_name="Test"):
    """Comprehensive model evaluation"""
    model.eval()
    all_preds = []
    all_labels = []
    all_probs = []

    print(f"🔍 Evaluating model on {dataset_name} set...")

    with torch.no_grad():
        for data, target in tqdm(data_loader, desc=f"Evaluating {dataset_name}"):
            data = data.to(device)
            output = model(data)

            # Get probabilities and predictions
            probs = torch.softmax(output, dim=1)
            _, preds = torch.max(output, 1)

            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(target.numpy())
            all_probs.extend(probs.cpu().numpy())

    # Calculate metrics
    accuracy = accuracy_score(all_labels, all_preds)
    cm = confusion_matrix(all_labels, all_preds)

    print(f"\n📊 {dataset_name} Results:")
    print(f"Accuracy: {accuracy*100:.2f}%")
    print(f"Total samples: {len(all_labels)}")
    print(f"Correct predictions: {sum(np.array(all_preds) == np.array(all_labels))}")

    # Detailed classification report
    class_names = ['Bonafide', 'Spoof']
    print(f"\nClassification Report:")
    print(classification_report(all_labels, all_preds, target_names=class_names))

    # Plot confusion matrix
    plt.figure(figsize=(8, 6))
    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=class_names)
    disp.plot(cmap='Blues', values_format='d')
    plt.title(f'Confusion Matrix - {dataset_name} Set')
    plt.show()

    return accuracy, all_preds, all_labels, all_probs

# Load best model
model_save_path = f"/kaggle/working/best_{SELECTED_MODEL}_mfcc_model.pth"
if os.path.exists(model_save_path):
    model.load_state_dict(torch.load(model_save_path))
    print(f"✅ Loaded best model from {model_save_path}")
else:
    print("⚠️  Best model not found, using current model state")

# Evaluate on validation set
val_acc, val_preds, val_labels, val_probs = evaluate_model(model, dev_loader, "Validation")

# ==============================================================================
# STEP 11: FINAL STATISTICS - FIXED VERSION
# ==============================================================================

print("=" * 50)
print("STEP 10: FINAL STATISTICS")
print("=" * 50)

def print_final_stats():
    """Print comprehensive system and model statistics"""
    print("🏆 FINAL RESULTS SUMMARY")
    print("=" * 30)

    # Get the best training and validation accuracies from history
    best_train_acc = max(history['train_acc']) if history['train_acc'] else 0.0
    best_val_acc = max(history['val_acc']) if history['val_acc'] else val_acc * 100

    print(f"Best Training Accuracy: {best_train_acc:.2f}%")
    print(f"Best Validation Accuracy: {best_val_acc:.2f}%")

    # Training progress summary
    print(f"Final Training Accuracy: {history['train_acc'][-1]:.2f}%")
    print(f"Final Validation Accuracy: {history['val_acc'][-1]:.2f}%")
    print(f"Total Epochs Trained: {len(history['train_acc'])}")

    print(f"\n📈 DATASET STATISTICS")
    print("=" * 30)
    print(f"Training samples: {len(train_dataset):,}")
    print(f"Validation samples: {len(dev_dataset):,}")
    print(f"Total processed: {len(train_dataset) + len(dev_dataset):,}")

    # Dataset distribution
    train_bonafide = sum(1 for label in train_dataset.labels if label == 0)
    train_spoof = len(train_dataset.labels) - train_bonafide
    val_bonafide = sum(1 for label in dev_dataset.labels if label == 0)
    val_spoof = len(dev_dataset.labels) - val_bonafide

    print(f"Training - Bonafide: {train_bonafide:,}, Spoof: {train_spoof:,}")
    print(f"Validation - Bonafide: {val_bonafide:,}, Spoof: {val_spoof:,}")

    print(f"\n🎯 MODEL ARCHITECTURE")
    print("=" * 30)
    print(f"Model: Vision Transformer ({SELECTED_MODEL.upper()})")
    print(f"Input size: 224×224×3")
    print(f"Number of classes: 2 (Bonafide, Spoof)")
    print(f"Total parameters: {sum(p.numel() for p in model.parameters()):,}")
    print(f"Trainable parameters: {sum(p.numel() for p in model.parameters() if p.requires_grad):,}")

    print(f"\n🎵 AUDIO PROCESSING")
    print("=" * 30)
    print(f"MFCC Features: 40 coefficients")
    print(f"Sample Rate: 16kHz")
    print(f"Max Sequence Length: 500 frames")
    print(f"Image Size: 224×224 (resized for ViT)")

    print(f"\n⚙️ TRAINING CONFIGURATION")
    print("=" * 30)
    print(f"Batch Size: {train_loader.batch_size}")
    print(f"Optimizer: AdamW")
    print(f"Loss Function: CrossEntropyLoss")
    print(f"Device: {device}")

    print(f"\n💾 SYSTEM RESOURCES")
    print("=" * 30)
    try:
        print_system_stats()
    except Exception as e:
        print(f"System stats unavailable: {e}")

    print(f"\n📊 PERFORMANCE ANALYSIS")
    print("=" * 30)
    if len(history['val_acc']) > 1:
        val_improvement = history['val_acc'][-1] - history['val_acc'][0]
        print(f"Validation accuracy improvement: {val_improvement:+.2f}%")

        # Find epoch with best validation accuracy
        best_epoch = history['val_acc'].index(max(history['val_acc'])) + 1
        print(f"Best validation accuracy achieved at epoch: {best_epoch}")

    print(f"\n💾 SAVED FILES")
    print("=" * 30)
    model_path = f"/kaggle/working/best_{SELECTED_MODEL}_mfcc_model.pth"
    print(f"Best model: {model_path}")
    print(f"Training history: /kaggle/working/training_history.json")

    print(f"\n🎉 TRAINING COMPLETED SUCCESSFULLY!")

print_final_stats()

# Save final training history
import json
with open("/kaggle/working/training_history.json", 'w') as f:
    json.dump(history, f, indent=2)

print("\n💾 Training history saved to: /kaggle/working/training_history.json")

# Additional analysis - Training convergence
print("\n📈 TRAINING CONVERGENCE ANALYSIS")
print("=" * 50)

if len(history['train_acc']) > 0:
    print("Epoch-by-Epoch Results:")
    print("-" * 60)
    print(f"{'Epoch':<6} {'Train Acc':<12} {'Val Acc':<12} {'Train Loss':<12} {'Val Loss':<10}")
    print("-" * 60)

    for i in range(len(history['train_acc'])):
        epoch = i + 1
        train_acc_val = history['train_acc'][i]
        val_acc_val = history['val_acc'][i]
        train_loss_val = history['train_loss'][i]
        val_loss_val = history['val_loss'][i]

        # Highlight best validation accuracy
        marker = "🎯" if val_acc_val == max(history['val_acc']) else "  "

        print(f"{epoch:<6} {train_acc_val:<12.2f} {val_acc_val:<12.2f} {train_loss_val:<12.4f} {val_loss_val:<10.4f} {marker}")

print("\n🎊 ALL STEPS COMPLETED SUCCESSFULLY!")
print("=" * 50)

def predict_from_file(model_path, npy_path):
    import torch
    import numpy as np
    from torchvision.models import vit_b_32, ViT_B_32_Weights
    import os

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    # Load model
    weights = ViT_B_32_Weights.DEFAULT
    model = vit_b_32(weights=weights)
    model.heads.head = torch.nn.Linear(model.heads.head.in_features, 2)
    model.load_state_dict(torch.load(model_path, map_location=device))
    model = model.to(device)
    model.eval()

    # Load and preprocess MFCC
    mfcc = np.load(npy_path)
    mfcc = (mfcc - np.mean(mfcc)) / (np.std(mfcc) + 1e-9)
    mfcc = np.expand_dims(mfcc, axis=0)     # (1, H, W)
    mfcc = np.repeat(mfcc, 3, axis=0)       # (3, H, W)
    tensor = torch.tensor(mfcc, dtype=torch.float32).unsqueeze(0).to(device)  # (1, 3, H, W)

    # Predict
    with torch.no_grad():
        output = model(tensor)
        prediction = torch.argmax(output, dim=1).item()

    return prediction, output.softmax(dim=1).squeeze().tolist()

model_path = "/kaggle/working/best_vit_b_32_mfcc_model.pth"
test_file = "/kaggle/working/mfcc_npy/test/LA_E_1100003_spoof.npy"

pred, conf = predict_from_file(model_path, test_file)

print("🔍 Prediction:", "bonafide" if pred == 0 else "spoof")
print("📊 Confidence Scores:", conf)