# -*- coding: utf-8 -*-
"""vit-fakeavceleb.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_3edwBXm5B_s_Lrh8EyiRvLxXugb4jyI
"""

import os
import gc
import json
import librosa
import numpy as np
from tqdm import tqdm
from pathlib import Path
from moviepy.video.io.VideoFileClip import VideoFileClip
import warnings
import torch
import psutil
from datetime import datetime
warnings.filterwarnings("ignore")

# --- MEMORY MANAGEMENT ---
def clear_memory():
    """Clear memory and run garbage collection"""
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

def get_memory_usage():
    """Get current memory usage"""
    process = psutil.Process(os.getpid())
    mem_gb = process.memory_info().rss / 1024 / 1024 / 1024
    if torch.cuda.is_available():
        gpu_mem = torch.cuda.memory_allocated() / 1024**3
        return f"RAM: {mem_gb:.2f}GB, GPU: {gpu_mem:.2f}GB"
    return f"RAM: {mem_gb:.2f}GB"

# --- PATH SETUP ---
SOURCE_DIR = "/kaggle/input/fakeavcaleb/FakeAVCeleb_v1.2"
WORK_DIR = "/kaggle/working"
AUDIO_DIR = os.path.join(WORK_DIR, "Audio")
PROGRESS_FILE = os.path.join(WORK_DIR, "audio_progress.json")

os.makedirs(AUDIO_DIR, exist_ok=True)

# --- CONFIG ---
BATCH_SIZE = 100       # Increased for audio-only processing
CLEAR_EVERY = 20       # Clear memory every N files
MFCC_FEATURES = 40
AUDIO_DURATION = 10    # Limit audio duration
SR = 16000            # Sample rate

# --- PROGRESS TRACKING ---
def load_progress():
    """Load processing progress from file"""
    if os.path.exists(PROGRESS_FILE):
        try:
            with open(PROGRESS_FILE, 'r') as f:
                return json.load(f)
        except:
            pass
    return {
        'processed_files': set(),
        'total_processed': 0,
        'failed_files': [],
        'start_time': datetime.now().isoformat()
    }

def save_progress(progress):
    """Save processing progress to file"""
    progress_copy = progress.copy()
    progress_copy['processed_files'] = list(progress['processed_files'])
    progress_copy['last_update'] = datetime.now().isoformat()

    with open(PROGRESS_FILE, 'w') as f:
        json.dump(progress_copy, f, indent=2)

# --- GET FILES ---
all_mp4_files = sorted(list(Path(SOURCE_DIR).rglob("*.mp4")))
total_files = len(all_mp4_files)
print(f"🎯 Total .mp4 files found: {total_files}")

# Load existing progress
progress = load_progress()
processed_files = set(progress['processed_files'])
print(f"📋 Previously processed: {len(processed_files)} files")
print(f"🔄 Remaining to process: {total_files - len(processed_files)} files")

# --- AUDIO EXTRACTION FUNCTION ---
def extract_mfcc_features(video_path, save_path):
    """Extract MFCC features from video audio"""
    if os.path.exists(save_path):
        return True

    tmp_wav = None
    try:
        # Use temporary file in working directory
        tmp_wav = os.path.join(WORK_DIR, f"temp_audio_{os.getpid()}.wav")

        # Extract audio with optimized settings
        with VideoFileClip(str(video_path)) as video:
            audio = video.audio
            if audio is None:
                return False

            # Save temporary audio file with compression
            audio.write_audiofile(tmp_wav, verbose=False, logger=None,
                                bitrate="64k", ffmpeg_params=["-ac", "1"])

        # Load and process audio with librosa
        y, sr = librosa.load(tmp_wav, sr=SR, duration=AUDIO_DURATION)
        if len(y) < 1024:  # Too short audio
            return False

        # Extract MFCC features
        mfcc = librosa.feature.mfcc(
            y=y,
            sr=sr,
            n_mfcc=MFCC_FEATURES,
            hop_length=512,
            n_fft=2048,
            window='hann'
        )

        # Also extract additional features for better representation
        spectral_centroids = librosa.feature.spectral_centroid(y=y, sr=sr)
        zero_crossings = librosa.feature.zero_crossing_rate(y)

        # Combine features
        features = np.vstack([mfcc, spectral_centroids, zero_crossings])

        # Save as compressed numpy array
        np.save(save_path, features.astype(np.float32))
        return True

    except Exception as e:
        print(f"❌ MFCC extraction failed for {video_path.name}: {str(e)}")
        return False
    finally:
        # Clean up temporary file
        if tmp_wav and os.path.exists(tmp_wav):
            try:
                os.remove(tmp_wav)
            except:
                pass

# --- MAIN PROCESSING FUNCTION ---
def process_audio_files():
    """Process all video files for audio MFCC extraction"""

    remaining_files = [f for f in all_mp4_files
                      if f.stem not in processed_files]

    if not remaining_files:
        print("✅ All audio files already processed!")
        return 0, 0  # Return success and failed counts

    print(f"🚀 Starting MFCC extraction for {len(remaining_files)} files")
    print(f"💾 {get_memory_usage()}")

    successful = 0
    failed = 0

    try:
        for start in range(0, len(remaining_files), BATCH_SIZE):
            batch = remaining_files[start:start + BATCH_SIZE]
            batch_success = 0

            print(f"\n🔄 Processing batch {start//BATCH_SIZE + 1}/{(len(remaining_files)-1)//BATCH_SIZE + 1}")
            print(f"📁 Files {start + 1} to {start + len(batch)} of {len(remaining_files)}")

            for i, file_path in enumerate(tqdm(batch, desc="Extracting MFCC")):
                filename = file_path.stem

                # Skip if already processed
                if filename in processed_files:
                    continue

                # Output path
                audio_out = os.path.join(AUDIO_DIR, filename + ".npy")

                # Process audio
                try:
                    if extract_mfcc_features(file_path, audio_out):
                        batch_success += 1
                        successful += 1
                    else:
                        failed += 1
                        progress['failed_files'].append(filename)

                    # Mark as processed regardless of success
                    processed_files.add(filename)

                except Exception as e:
                    print(f"❌ Error processing {filename}: {str(e)}")
                    failed += 1
                    progress['failed_files'].append(filename)
                    processed_files.add(filename)
                    continue

                # Memory management
                if (i + 1) % CLEAR_EVERY == 0:
                    clear_memory()

            # Update progress after each batch
            progress['processed_files'] = processed_files
            progress['total_processed'] = len(processed_files)
            save_progress(progress)
            clear_memory()

            print(f"✅ Batch completed: Success={batch_success}, Failed={len(batch)-batch_success}")
            print(f"📊 Overall progress: {len(processed_files)}/{total_files} files")
            print(f"💾 {get_memory_usage()}")

    except KeyboardInterrupt:
        print("\n⚠️ Processing interrupted by user")
        progress['processed_files'] = processed_files
        progress['total_processed'] = len(processed_files)
        save_progress(progress)
        print("💾 Progress saved. You can resume later.")
        return successful, failed  # Return counts even when interrupted
    except Exception as e:
        print(f"\n❌ Unexpected error: {str(e)}")
        progress['processed_files'] = processed_files
        progress['total_processed'] = len(processed_files)
        save_progress(progress)
        return successful, failed  # Return counts even on error

    return successful, failed

# --- RUN PROCESSING ---
if __name__ == "__main__":
    print("🎵 FakeAVCeleb Audio MFCC Extraction")
    print("=" * 50)

    # Handle the case where process_audio_files might return None
    result = process_audio_files()
    if result is not None:
        successful, failed = result
    else:
        # Fallback values if somehow None is returned
        successful, failed = 0, 0

    # Final summary
    print("\n🎉 Audio processing completed!")
    print(f"✅ Successfully processed: {successful}")
    print(f"❌ Failed to process: {failed}")
    print(f"📁 Total files processed: {len(processed_files)}")
    print(f"💾 Final memory usage: {get_memory_usage()}")

    # Show some statistics about extracted files
    audio_files = list(Path(AUDIO_DIR).glob("*.npy"))
    print(f"🎵 Total MFCC files saved: {len(audio_files)}")

    if audio_files:
        # Sample file size
        sample_size = os.path.getsize(audio_files[0]) / 1024  # KB
        total_size = sum(os.path.getsize(f) for f in audio_files) / (1024*1024)  # MB
        print(f"📊 Average file size: {sample_size:.2f} KB")
        print(f"📊 Total data size: {total_size:.2f} MB")

    # Clean up progress file if everything is done
    if len(processed_files) >= total_files:
        try:
            os.remove(PROGRESS_FILE)
            print("🧹 Cleaned up progress file")
        except:
            pass